- hosts: smtp

  roles:
    - { role: digitalocean_firewall,
        vars: {
            digitalocean_firewall_name: fw-smtp-servers,
            digitalocean_firewall_rule: ssh-inbound,
            digitalocean_firewall_rule_status: enable
        },
        tags: [ ssh_on ]
      }

    - { role: centos_selinux,
        vars: {
            centos_selinux_state: disabled  # for demo only
        },
        tags: selinux }

    - { role: centos_certbot_easydns,
        vars: {
            centos_certbot_easydns_api: "{{ easydns_api }}",
            centos_certbot_easydns_token: "{{ easydns_token }}",
            centos_certbot_easydns_key: "{{ easydns_key }}",
            centos_certbot_easydns_domain: "{{ mail_server_domainname }}",
            centos_certbot_easydns_email: "{{ mail_server_domainname_contact }}"
        },
        tags: certbot }

    - { role: centos_dovecot_tls,
        vars: {
            dovecot_tls_server_domainname: "{{ mail_server_domainname }}"
        },
        tags: dovecot }

    - { role: digitalocean_firewall,
        vars: {
            digitalocean_firewall_name: fw-smtp-servers,
            digitalocean_firewall_rule: dovecot-inbound,
            digitalocean_firewall_rule_status: enable
        },
        tags: [ dovecot_on ]
      }

    - { role: centos_postfix,
        vars: {
            centos_postfix_server_domain: "{{ mail_server_domainname }}",
            centos_postfix_server_fqdn: "{{ mail_server_fqdn }}",
            centos_postfix_sender_login_map: "{{ dovecot_mailboxes }}",
            centos_postfix_virtual_alias_map: "{{ postfix_virtual_aliases }}",
            centos_postfix_hosted_domains: "{{ postfix_hosted_domains }}"
        },
        tags: postfix }

    - { role: digitalocean_firewall,
        vars: {
            digitalocean_firewall_name: fw-smtp-servers,
            digitalocean_firewall_rule: postfix-inbound,
            digitalocean_firewall_rule_status: enable
        },
        tags: [ postfix_on ]
      }

    - { role: digitalocean_firewall,
        vars: {
            digitalocean_firewall_name: fw-smtp-servers,
            digitalocean_firewall_rule: ssh-inbound,
            digitalocean_firewall_rule_status: disable
        },
        tags: [ ssh_off ]
      }
