- hosts: visit_redis

  roles:
    - { role: digitalocean_firewall,
        vars: {
            digitalocean_firewall_name: fw-web-servers,
            digitalocean_firewall_rule: ssh-inbound,
            digitalocean_firewall_rule_status: enable
        },
        tags: [ ssh_on ]
      }

    - { role: centos_selinux,
        vars: {
            centos_selinux_state: disabled  # for demo only
        },
        tags: selinux }

    - { role: centos_yum_update,
        vars: {
            yum_update_reboot: true  # for demo only
        },
        tags: yumupdate }

    - { role: centos_iptables,
        vars: {
            firewall_ruleset: visit_redis  # for demo only
        },
        tags: iptables }

#    - { role: digitalocean_firewall,
#        vars: {
#            digitalocean_firewall_name: fw-web-servers,
#            digitalocean_firewall_rule: ssh-inbound,
#            digitalocean_firewall_rule_status: disable
#        },
#        tags: [ ssh_off ]
#      }
