- name: ensure opendmarc is installed
  yum:
      name: opendmarc
      state: present
  tags: opendmarc

- name: ensure opendmarc.conf is updated
  template:
    src: opendmarc.conf.j2
    dest: /etc/opendmarc.conf
    mode: 0644
    owner: root
    group: root
  tags: opendmarc

- name: restart opendmarc
  service:
      name: opendmarc
      state: restarted
      enabled: yes
  tags: opendmarc

- name: Reset opendmarc run dir perms, giving postfix access
  file:
      path: /var/run/opendmarc/
      state: directory
      mode: '0755'

- name: add cron to ensure postfix has permissions to unix:socket
  cron:
    name: "opendmarc permissions reset"
    special_time: reboot
    job: "chmod 755 /var/run/opendmarc/"
