---
# tasks file for roles/centos_postfix

- name: ensure postfix is installed
  yum:
      name: postfix
      state: present

- name: send postfix main.cf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    mode: 0644
    owner: root
    group: root

- name: ensure map_sender_login is up to date
  lineinfile:
    path: /etc/postfix/map_sender_login
    regexp: "^{{ item.login }} {{ item.login }}"
    line: "{{ item.login }} {{ item.login }}"
    mode: 0644
    owner: root
    group: root
    create: yes
  with_items: "{{ centos_postfix_sender_login_map | default([]) }}"
  no_log: yes
  register: centos_postfix_sender_login_map_result

- name: update map_sender_login db
  command: /usr/sbin/postmap hash:/etc/postfix/map_sender_login
  when: centos_postfix_sender_login_map_result.changed

- name: ensure map_virtual_alias is up to date
  lineinfile:
    path: /etc/postfix/map_virtual_alias
    regexp: "^{{ item }}"
    line: "{{ item }}"
    mode: 0644
    owner: root
    group: root
    create: yes
  with_items: "{{ centos_postfix_virtual_alias_map | default([]) }}"
  no_log: yes
  register: centos_postfix_virtual_alias_map_result

- name: update map_virtual_alias db
  command: /usr/sbin/postmap hash:/etc/postfix/map_virtual_alias
  when: centos_postfix_virtual_alias_map_result.changed

- name: restart postfix
  service:
      name: postfix
      state: restarted
      enabled: yes
