- name: ensure opendkim is installed
  yum:
      name: opendkim
      state: present
  tags: opendkim

- name: ensure opendkim.conf is updated
  template:
    src: opendkim.conf.j2
    dest: /etc/opendkim.conf
    mode: 0644
    owner: root
    group: root
  tags: opendkim

- name: ensure DKIM SingingTable is up to date
  lineinfile:
    path: /etc/opendkim/SigningTable
    regexp: "{{ item }}"
    line: "*@{{ item }} {{ item }}"
    mode: 0644
    owner: opendkim
    group: opendkim
    create: yes
  with_items: "{{ centos_postfix_hosted_domains | default([]) }}"
  tags: opendkim

- name: ensure DKIM KeyTable is up to date
  lineinfile:
    path: /etc/opendkim/KeyTable
    regexp: "^{{ item }} {{ item }}:mail:/etc/opendkim/keys/{{ item }}.dkim.private"
    line: "{{ item }} {{ item }}:mail:/etc/opendkim/keys/{{ item }}.dkim.private"
    mode: 0644
    owner: opendkim
    group: opendkim
    create: yes
  with_items: "{{ centos_postfix_hosted_domains | default([]) }}"
  tags: opendkim

- name: update DKIM domain keys
  copy:
      content: "{{ item.private_key }}"
      dest: "/etc/opendkim/keys/{{ item.name }}.dkim.private"
      owner: opendkim
      group: opendkim
      mode: 0400
  with_items: "{{ postfix_hosted_domains_dkim_keys }}"
  no_log: yes
  tags: opendkim

- name: restart opendkim
  service:
      name: opendkim
      state: restarted
      enabled: yes
  tags: opendkim

- name: Reset opendkim run dir perms, giving postfix access
  file:
      path: /var/run/opendkim/
      state: directory
      mode: '0755'

- name: add cron to ensure postfix has permissions to unix:socket
  cron:
    name: "opendkim permissions reset"
    special_time: reboot
    job: "chmod 755 /var/run/opendkim/"
